"""
Redesigned Quick Quiz — formative practice with immediate feedback.

Key UX changes vs. the previous implementation:
  * Immediate per-question feedback (correct/incorrect + AI explanation),
    which is the whole point of formative practice. Explanations were
    already generated by the backend but never shown.
  * Segmented progress that colours in as you go, plus a live streak chip.
  * Answer options are large tappable cards with A/B/C/D keys, not radios.
  * Ends on the shared full-screen results report (scrollable, filterable)
    instead of a clipped fixed-size dialog.
"""

import time

import flet as ft

from src.components import study_ui as ui

_LETTERS = ["A", "B", "C", "D", "E", "F"]


def build_quiz(
    page: ft.Page,
    questions: list,
    *,
    on_exit,
    on_restart,
    haptics: "ui.Haptics | None" = None,
):
    """Returns a Control for the full quiz session."""
    total = len(questions)
    if total == 0:
        return ui.empty_state(
            ft.Icons.QUIZ_OUTLINED,
            "No quiz questions yet",
            "Generate questions from your study material first,\nthen come back for a quiz.",
            "Back to Hub",
            on_exit,
        )

    state = {
        "index": 0,
        "answered": False,
        "streak": 0,
        "best_streak": 0,
        "records": [],
        "started": time.time(),
        "q_started": time.time(),
    }

    root = ft.Container(expand=True)
    progress = ui.SegmentedProgress(total, active_color=ft.Colors.PRIMARY)
    counter = ft.Text("", size=12, weight=ft.FontWeight.W_700, color=ui.muted(0.70))

    streak_pill = ui.pill("0 streak", ui.C_WARN, icon=ft.Icons.LOCAL_FIRE_DEPARTMENT_ROUNDED)
    score_pill = ui.pill("0 correct", ui.C_CORRECT, icon=ft.Icons.CHECK_CIRCLE_ROUNDED)

    question_text = ft.Text(
        "",
        size=17,
        weight=ft.FontWeight.W_700,
        color=ft.Colors.ON_SURFACE,
        selectable=True,
    )
    options_col = ft.Column(spacing=9)

    # Feedback panel — hidden until an answer is submitted.
    fb_icon = ft.Icon(ft.Icons.CHECK_CIRCLE_ROUNDED, size=20, color=ui.C_CORRECT)
    fb_title = ft.Text("", size=14, weight=ft.FontWeight.W_800, color=ui.C_CORRECT)
    fb_expl = ft.Text("", size=12, color=ui.muted(0.80), selectable=True)
    feedback = ft.Container(
        visible=False,
        padding=13,
        border_radius=ui.RADIUS_MD,
        animate_opacity=ft.Animation(ui.DUR_BASE, ui.CURVE_OUT),
        opacity=0.0,
        content=ft.Column(
            spacing=7,
            controls=[
                ft.Row(spacing=8, controls=[fb_icon, fb_title]),
                fb_expl,
            ],
        ),
    )

    next_btn = ft.Container(visible=False)

    def _current():
        return questions[state["index"]] or {}

    def _sync_chips():
        streak_pill.content.controls[-1].value = f"{state['streak']} streak"
        correct_so_far = sum(
            1 for r in state["records"] if r["chosen_index"] == r["correct_index"]
        )
        score_pill.content.controls[-1].value = f"{correct_so_far} correct"

    def _option_tile(idx: int, label: str):
        letter_box = ft.Container(
            width=27,
            height=27,
            border_radius=8,
            bgcolor=ui.tint(ft.Colors.ON_SURFACE, 0.06),
            alignment=ft.Alignment.CENTER,
            animate=ft.Animation(ui.DUR_FAST, ui.CURVE_OUT),
            content=ft.Text(
                _LETTERS[idx] if idx < len(_LETTERS) else str(idx + 1),
                size=11,
                weight=ft.FontWeight.W_800,
                color=ui.muted(0.60),
            ),
        )
        body = ft.Text(label, size=13, color=ft.Colors.ON_SURFACE, expand=True, selectable=False)
        trailing = ft.Icon(ft.Icons.CIRCLE_OUTLINED, size=17, color=ui.hairline(0.18))

        tile = ft.Container(
            padding=ft.Padding.symmetric(horizontal=13, vertical=13),
            border_radius=ui.RADIUS_MD,
            bgcolor=ft.Colors.SURFACE,
            border=ft.Border.all(1.5, ui.hairline(0.12)),
            ink=True,
            animate=ft.Animation(ui.DUR_BASE, ui.CURVE_OUT),
            scale=1.0,
            animate_scale=ft.Animation(ui.DUR_FAST, ui.CURVE_OUT),
            on_click=lambda _, i=idx: _answer(i),
            content=ft.Row(
                spacing=11,
                vertical_alignment=ft.CrossAxisAlignment.CENTER,
                controls=[letter_box, body, trailing],
            ),
        )
        # Stash the parts we need to restyle after answering.
        tile.data = {"letter": letter_box, "trailing": trailing, "index": idx}
        return tile

    def _render_question():
        q = _current()
        state["answered"] = False
        state["q_started"] = time.time()

        counter.value = f"Question {state['index'] + 1} of {total}"
        question_text.value = str(q.get("question") or "—")
        progress.set_current(state["index"])

        options_col.controls.clear()
        for i, opt in enumerate(q.get("options") or []):
            options_col.controls.append(_option_tile(i, str(opt)))

        feedback.visible = False
        feedback.opacity = 0.0
        next_btn.visible = False
        _sync_chips()

    def _answer(chosen: int):
        if state["answered"]:
            return
        state["answered"] = True

        q = _current()
        correct_i = q.get("answer")
        try:
            correct_i = int(correct_i)
        except (TypeError, ValueError):
            correct_i = -1
        is_right = chosen == correct_i

        # Restyle every option to show the outcome.
        for tile in options_col.controls:
            meta = tile.data or {}
            i = meta.get("index")
            letter = meta.get("letter")
            trailing = meta.get("trailing")
            if i == correct_i:
                tile.bgcolor = ui.tint(ui.C_CORRECT, 0.10)
                tile.border = ft.Border.all(1.5, ui.tint(ui.C_CORRECT, 0.55))
                letter.bgcolor = ui.C_CORRECT
                letter.content.color = ft.Colors.ON_PRIMARY
                trailing.name = ft.Icons.CHECK_CIRCLE_ROUNDED
                trailing.color = ui.C_CORRECT
            elif i == chosen:
                tile.bgcolor = ui.tint(ui.C_WRONG, 0.10)
                tile.border = ft.Border.all(1.5, ui.tint(ui.C_WRONG, 0.55))
                letter.bgcolor = ui.C_WRONG
                letter.content.color = ft.Colors.ON_PRIMARY
                trailing.name = ft.Icons.CANCEL_ROUNDED
                trailing.color = ui.C_WRONG
            else:
                tile.opacity = 0.55
            tile.on_click = None

        if is_right:
            state["streak"] += 1
            state["best_streak"] = max(state["best_streak"], state["streak"])
            progress.mark(state["index"], ui.C_CORRECT)
            fb_icon.name = ft.Icons.CHECK_CIRCLE_ROUNDED
            fb_icon.color = ui.C_CORRECT
            fb_title.value = (
                f"Correct — {state['streak']} in a row!"
                if state["streak"] > 1
                else "Correct!"
            )
            fb_title.color = ui.C_CORRECT
            feedback.bgcolor = ui.tint(ui.C_CORRECT, 0.07)
            feedback.border = ft.Border.all(1, ui.tint(ui.C_CORRECT, 0.25))
            if haptics:
                haptics.light()
        else:
            state["streak"] = 0
            progress.mark(state["index"], ui.C_WRONG)
            fb_icon.name = ft.Icons.CANCEL_ROUNDED
            fb_icon.color = ui.C_WRONG
            fb_title.value = "Not quite"
            fb_title.color = ui.C_WRONG
            feedback.bgcolor = ui.tint(ui.C_WRONG, 0.07)
            feedback.border = ft.Border.all(1, ui.tint(ui.C_WRONG, 0.25))
            if haptics:
                haptics.medium()

        expl = q.get("explanation")
        fb_expl.value = str(expl) if expl else ""
        fb_expl.visible = bool(expl)
        feedback.visible = True
        feedback.opacity = 1.0

        state["records"].append(
            {
                "question": q.get("question") or "",
                "options": list(q.get("options") or []),
                "correct_index": correct_i,
                "chosen_index": chosen,
                "explanation": expl,
                "flagged": False,
                "seconds": int(time.time() - state["q_started"]),
            }
        )

        is_last = state["index"] >= total - 1
        next_btn.content = ui.primary_button(
            "See results" if is_last else "Next question",
            lambda _: _next(),
            icon=ft.Icons.ASSESSMENT_ROUNDED if is_last else ft.Icons.ARROW_FORWARD_ROUNDED,
            expand=True,
            height=48,
        )
        next_btn.visible = True
        _sync_chips()
        page.update()

    def _next():
        if state["index"] >= total - 1:
            _show_results()
            return
        state["index"] += 1
        _render_question()
        page.update()

    def _show_results():
        progress.fill_all()
        root.content = ui.build_results_view(
            page,
            title="Quick Quiz",
            accent=ft.Colors.PRIMARY,
            records=state["records"],
            elapsed_seconds=int(time.time() - state["started"]),
            on_retry=on_restart,
            on_exit=on_exit,
            show_pass_band=False,  # practice, not a graded assessment
        )
        page.update()

    # Keyboard: A-F / 1-6 to answer, Enter to advance.
    def _on_key(e: ft.KeyboardEvent):
        key = (e.key or "").lower()
        if key == "escape":
            on_exit()
            return
        if state["answered"]:
            if key in ("enter", " ", "space"):
                _next()
            return
        opts = len(_current().get("options") or [])
        if key.isdigit() and 1 <= int(key) <= opts:
            _answer(int(key) - 1)
        elif len(key) == 1 and key.upper() in _LETTERS[:opts]:
            _answer(_LETTERS.index(key.upper()))

    page.on_keyboard_event = _on_key

    _render_question()

    compact = ui.is_compact(page)
    body = ft.Column(
        spacing=16,
        controls=[
            ui.surface_card(
                ft.Column(
                    spacing=13,
                    controls=[
                        ui.section_label("Question"),
                        question_text,
                    ],
                ),
                padding=17,
            ),
            options_col,
            feedback,
            next_btn,
            ft.Container(height=24),
        ],
    )

    root.content = ft.Column(
        expand=True,
        spacing=0,
        controls=[
            ui.progress_header(counter, progress, right=[streak_pill, score_pill]),
            ft.Container(
                expand=True,
                content=ft.Column(
                    expand=True,
                    scroll=ft.ScrollMode.AUTO,
                    controls=[
                        ft.Container(
                            alignment=ft.Alignment.TOP_CENTER,
                            padding=ft.Padding.symmetric(
                                horizontal=14 if compact else 28, vertical=18
                            ),
                            content=ft.Container(
                                content=body, width=None if compact else 680
                            ),
                        )
                    ],
                ),
            ),
        ],
    )

    return root
